### ISSUE TITLE
Can multiple “deskhops” be connected to each other to achieve signal forwarding

### ISSUE THREAD

**Issue by buke18** [hrvach/deskhop#171]
looking at your project gave me this idea: If you are in a multi-function conference room with multiple monitors, can you use this tool to connect the display of several screens? Control the display of different screens for each screen, and connect all screens through one or several desktops to improve the efficiency and cleanliness of the meeting. If a desktop is connected to multiple screens, can several desktops be connected in parallel and then connected together to connect more screens?

**Comment by wences-dc-uba-ar** [comment]
Interesting idea, but ... have you found a way to connect monitors in deskhop?

**Comment by hrvach** [comment]
You can't connect the screens, that would take some dedicated multiplexing logic which hasn't been attempted yet. I've been looking into it, but due to the enormous bandwidth hdmi has with any half-decent resolution, anything that does really fast switching would require you to buffer at least half of one frame in order to be able to match horizontal and vertical sync signals and achieve instant transition. Some further experimentation needed... :)
