### ISSUE TITLE
Better function names

### ISSUE THREAD

**Issue by jalmeroth** [hrvach/deskhop#182]
Heya,

I know naming things in IT is hard, but I'm confused by this:

```cpp
void switch_output(device_t *, uint8_t);
void switch_desktop(device_t *state, output_t *output, int new_index, int direction);
void switch_screen( device_t *state, output_t *output, int output_to, int direction);
```
Can you tell me for sure, which one is used for moving the mouse from PC A to PC B? 

My proposal would be:
```cpp
void activate_dh_device(device_t *, uint8_t);
void switch_monitor(device_t *state, output_t *output, int new_index, int direction);
void switch_pc( device_t *state, output_t *output, int output_to, int direction);
```
… or something like this. What do you think?

**Comment by hrvach** [comment]
I completely agree, a lot of cleanup and refactoring is way overdue and it kind of shows many of these were created while trying to get something to work and then kept in the codebase because there were always more pressing issues to take care of.

There could be something like switch_physical_output() that does the physical output switching and switch_virtual_desktop() or something similar that does the virtual screen switching if needed, the third one could be something like activate_dh_board or activate_dh_output like you suggested. 

I'll move ahead and change these, please feel free to suggest any other issues you might find in need of refactoring - your advice is highly appreciated and any help is more than welcome!
