### ISSUE TITLE
Suggestion: Add holes to support clone Raspberry Pi Pico pinouts

### ISSUE THREAD

**Issue by Ardakilic** [hrvach/deskhop#39]
Hello,

There are some Raspberry Pi Pico clones, which are cheaper and have usb-c connectors, such as these:

![image](https://github.com/hrvach/deskhop/assets/2063957/01079f7b-6846-4655-8a13-b5ba2aa5cb9c)

Pinouts match 1:1 on these clone pico boards. 

However, since the current PCB design is for smd soldering only, it's too hard to solder these pico to the board.

If the soldering pads chould support both smd and through hole soldering, something like the center part of this PCB, it'd be way easier so solder these.

![2024_01_19_0uk_Kleki](https://github.com/hrvach/deskhop/assets/2063957/9b290549-5cc1-4993-98f7-b6f339ea9c79)

I'd appreciate if this is considered. Sorry I'm not a board designer, otherwise this would have been a pull request.

Thanks in advance!

**Comment by hrvach** [comment]
Can do, that's for clearly documenting it like this. The rev1 board is already in the works, I'll try to squeeze in this addition.

**Comment by OrpheeGT** [comment]
> Can do, that's for clearly documenting it like this. The rev1 board is already in the works, I'll try to squeeze in this addition.

Do you suggest to wait before ordering a new batch if some friends request for this great toy ?

**Comment by Ardakilic** [comment]
@OrpheeGT if you're looking for USB-C like I do in the end, I got similar but different clones for the time being. Found them on a Aliexpress seller. They worked nicely:

![image](https://github.com/hrvach/deskhop/assets/2063957/407da8b6-57a4-4192-a75e-088868db7ad9)

![telegram-cloud-photo-size-4-5893066022469092042-y](https://github.com/hrvach/deskhop/assets/2063957/c293c7f3-c5be-4c9a-8c90-ae3bf30c9bcd)

Tested yesterday with Win-MAC and MAC-MAC. Worked without issues.

However, I'd prefer these black clones. They have boot select built in and overall fells a better quality product.

**Comment by hrvach** [comment]
The planned changes have already been done, but I'm waiting for the boards/parts to confirm everything is OK and functional as expected. Maybe I'm a bit overly cautious, but that goes with the job :)

I'm adding the holes as an option so it's up to the user to decide - original Pico does lack some features like a reset button, but honestly I'm still sticking with the original because it's pretty cheap, stocked everywhere and also giving some symbolic support for the Raspberry Pi Foundation :)

Micro USB is OK, but I'm keeping it plugged in all the time so I don't know how it behaves after 5000 cycles :)

**Comment by hrvach** [comment]
Holes added in PCB v1.1.

**Comment by Ardakilic** [comment]
Awesome news, thank you! 🚀
