### ISSUE TITLE
Suggestion: configuration file

### ISSUE THREAD

**Issue by p3lim** [hrvach/deskhop#72]
Instead of hard-coding options, requiring a recompile and "flash" for every change, use the RPI ROM to store a configuration file that the firmware reads on boot (or on a keybind to reload).

Would be _extra_ nice if this could be mounted without interrupting the normal behavior, e.g. we could edit this file using the keyboard/mouse attached to it and then trigger a reload.

I've seen other firmware do things like this with the RP2040, KMK comes to mind.

**Comment by hrvach** [comment]
This is actually done, there is a configuration file stored in the last flash block, saving border switching details and some other things (order of outputs, which OS is an output connected to etc).

It's not a text config but a struct with some checksum data, etc. I opted out of uploading a traditional config file because implementing usb storage is potentially problematic from a security / data protection standpoint. Some options that currently need a rebuild to change will get keyboard config support.
